[tasks.setup]
condition = { files_modified = { input = [
    "./pyproject.toml",
    "uv.lock",
], output = [
    ".venv/timestamp.txt",
] } }
script = [
    "uv venv",
    "uv sync",
    "uv pip install -e .",
    "touch .venv/timestamp.txt",
]

[tasks.gen]
dependencies = ["setup"]
description = "generate code from proto files using Buf and betterproto"
script = ["source .venv/bin/activate", "pushd ../proto", "buf generate --debug", "popd"]

[tasks.mypy]
dependencies = ["setup"]
description = "run mypy"
script = ["uv run mypy src"]

[tasks.run-server]
dependencies = ["setup"]
description = "run the gRPC server"
script = ["uv run python src/server.py"]

[tasks.client]
dependencies = ["setup"]
description = "gRPC client"
script = ["uv run python src/client.py"]

[tasks.buf-curl]
description = "run buf and curl"
script = [
    "pushd ../proto",
    "buf curl --http2-prior-knowledge --schema pet/v1/pet.proto --data '{\"pet_id\": \"1\"}' --protocol grpc http://localhost:50051/pet.v1.PetStoreService/GetPet",
    "popd",
]
